@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

class mainGabriel {
  + mainGabriel(): 
  + adjustPrecision(double[][]): void
  + adjustValue(double): void
  + array1DToMatrix(double[], double[][]): double[][]
  + calculateEuclidianDistance(double[], double[][]): double[]
  + calculateFunction2(int, String, int): void
  + calculateFunction3(int, String, String, int): void
  + calculateMAE(double[][], double[][]): double
  + calculateMeanVector(double[][]): double[]
  + calculateWeights(double[], double[][]): double[]
  + centralizeImages(double[][], double[]): double[][]
  + checkAverageVector(): void
  + checkCalculateWeights(): void
  + checkCentralizeImage(): void
  + checkCloserVetor(double[]): int[]
  + checkCloserVetorTest(): void
  + checkConstructDiagonalMatrix(): void
  + checkCorrectParametersStructure(String[]): boolean
  + checkCsvLocation(String): boolean
  + checkDataBaseLocation(String): boolean
  + checkEuclidianDistance(): void
  + checkExistanceFileDirectory(String): void
  + checkFunctionOptions(int): boolean
  + checkGetColumn(): void
  + checkGetValuesAndIndexArray(): void
  + checkIfIsSymmetric(double[][]): boolean
  + checkIgualdadeMatrizes(double[][], double[][]): boolean
  + checkIgualdadeVetores(double[], double[]): boolean
  + checkMAETest(): void
  + checkMatrixToArray1D(): void
  + checkMultiplication(): void
  + checkMultiplicationEscalar(): void
  + checkNormalization(): void
  + checkReconstructImage(): void
  + checkSizeBoundaries(int, int): boolean
  + checkSubMatrix(): void
  + checkSubtractionColumns(): void
  + checkTranspose(): void
  + constructDiagonalMatrix(double[][]): double[][]
  + createSubMatrix(double[][], double[][]): double[][]
  + creationImage(int, double[], int, double[][], double[][]): double[]
  + decomposeMatrix(double[][]): EigenDecomposition
  + decomposeSymmetricMatrix(int, String): void
  + devTeam(): void
  + errorGeneral(String): void
  + fillArrayMax(int[]): void
  + fillMatrixFromCsv(String, double[][]): void
  + findMinMaxValues(double[][]): double[]
  + function1(int): void
  + function2(int): void
  + function3(int): void
  + function4(int): void
  + generateNewImage(int, String, int): void
  + getCSVFileNames(String): String[]
  + getColumn(double[][], int): double[]
  + getCsvDimensions(String): int[]
  + getCsvLocationFromArgs(String[], int): String
  + getCsvLocationFromUser(int): String
  + getDataBaseLocationFromArgs(String[]): String
  + getDataBaseLocationFromUser(): String
  + getEigenValues(double[][]): double[][]
  + getEigenVectors(double[][]): double[][]
  + getMatricesFromCsvFolder(String): double[][][]
  + getValuesAndIndexArray(double[][], int): double[][]
  + identifyClosestImage(int, String[], double[], double[][], double[][], double[][], double[][][], int): void
  + main(String[]): void
  + matrixToArray1D(double[][]): double[]
  + multiplyMatrices(double[][], double[][]): double[][]
  + multiplyMatrixEscalar(double[][], double): double[][]
  + normalize(double[][]): double[][]
  + normalizeImage(double[][], double, double): int[][]
  + populateLinearizedImages(double[][], double[][][]): void
  + populateWeightsMatrix(double[][], double[][], double[][]): void
  + printDistances(String[], double[], int, int): void
  + printFunction1(int, double[][], double[][], double): void
  + printFunction3(String[], int, double[], int, int): void
  + printHeaderFunction(String): void
  + printLine(int, String): void
  + printMatrix(double[][], String): void
  + printVector(String, double[]): void
  + printVectorTests(double[], String): void
  + quitApplication(): void
  + readCSVToMatrix(String): double[][]
  + receiveCsvLocation(String[], int): String
  + receiveDataBaseLocation(String[]): String
  + receiveExitConfirmation(String[]): void
  + receiveFunction(String[]): int
  + receiveNumberVectors(String[]): int
  + reconstructImage(double[], double[][], double[], int): double[]
  + reconstructImagesWithEigenfaces(int, String[], double[], double[][], double[][], double[][], double[][][], int): void
  + runInterative(): void
  + runNonInteractive(String[]): void
  + runNonInterativeOutputs(int, int, String, String[], double[][], double[][][], String): void
  + runTests(): void
  + saveImage(double[][], String, String, int): void
  + saveMatrixToFile(double[][], String, String, int): void
  + subtractionColumns(double[], double[]): double[]
  + transposeMatrix(double[][]): double[][]
  + uiCsvLocation(): void
  + uiDataBase(): void
  + uiDevTeam(): void
  + uiInitialMenu(): void
  + uiQuitParameterMenu(): void
  + uiVectorNumbers(): void
  + validateEigenVectors(double[][], int): int
  + verifyCsvLocation(int): String
  + verifyDataBaseLocation(): String
  + verifyFunction(): int
  + verifySymmetricMatrix(String, int): String
  + verifyVectorNumbers(): int
  + writeArrayAsImage(int[][], String): void
}

@enduml
